---
- hosts: localhost
  become: yes
  become_user: root
  roles:
    - ../roles/wazuh/ansible-wazuh-agent
  vars:
    wazuh_managers:
      - address: 10.15.37.47
        port: 1514
        protocol: tcp
        api_port: 55000
        api_proto: 'http'
        api_user: ansible
        max_retries: 5
        retry_interval: 5
    wazuh_agent_enrollment:
      manager_address: 10.15.37.47
    wazuh_custom_packages_installation_agent_enabled: True
    wazuh_custom_packages_installation_agent_deb_url: "https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.2.5-1_amd64.deb"
    wazuh_custom_packages_installation_agent_rpm_url: "https://packages.wazuh.com/4.x/yum/wazuh-agent-4.2.5-1.x86_64.rpm"