---
- hosts: localhost
  become: yes
  become_user: root
  roles:
    - ../roles/wazuh/ansible-wazuh-agent
  vars:
    wazuh_managers:
      - address: 10.15.37.47
        port: 1514
        protocol: tcp
        api_port: 55000
        api_proto: 'http'
        api_user: ansible
        max_retries: 5
        retry_interval: 5
    wazuh_agent_authd:
      registration_address: 10.15.37.47
      enable: true
      port: 1515
      ssl_agent_ca: null
      ssl_auto_negotiate: 'no'
      groups: ['hub-wla-prod']
    wazuh_agent_enrollment:
      manager_address: 10.15.37.47
      groups: hub-wla-prod